name: Build and Publish Python Package to TestPyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-upload:
    name: Build and upload to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pytaifex
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Build package
        run: uv build

      - name: Publish package distributions to TestPyPI
        run: uv publish --index testpypi --trusted-publishing automatic
